#!/usr/bin/env bash

set -eu

export links
export make_mpet
export contigs_path
export mpet_r1_path
export mpet_r2_path
export fof
export outdir

links="$(readlink -f bin/links/LINKS)"
make_mpet="$(readlink -f bin/links/tools/makeMPETOutput2EQUALfiles.pl)"

mpet_r1=output/long_mate_pairs/lmp_r1.fa
mpet_r2=output/long_mate_pairs/lmp_r2.fa
mpet_r1_path="$(readlink -f "${mpet_r1}")"
mpet_r2_path="$(readlink -f "${mpet_r2}")"

contigs=data/contigs/final.scaffolds.fa
contigs_path="$(readlink -f "${contigs}")"

# output
outdir="output/links_mpet"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# run weird LINKS tool
# (
# cd "${outdir}" || exit 1
# "${make_mpet}" "${mpet_r1_path}" "${mpet_r2_path}" 0
# )

# long read file-of-filenames, ok then...?
mpet="${mpet_r1}_paired.fa"
mpet_path="$(readlink -f "${mpet}")"
fof="$(mktemp --suffix=.txt)"
cat <<- _EOF_ > "${fof}"
${mpet_path}
_EOF_

# IN THE LINKS MANUAL:
# When doing so, ensure that -t is set to extract at least ~5 kmer pairs/MPET
# pair As a rule of thumb, -l should be set to at least double that value (-l
# 10 in this case)
# with minimum length of 40 b reads in the splitnextera output, i calculate
# that you could generate 13 15-mers from a 40 b read, so I set l to 25.

(
cd "${outdir}" || exit 1
"${links}" \
    -f "${contigs_path}" \
    -s "${fof}" \
    -m 1 \
    -d 3103 \
    -l 25 \
    -b "meraculous71_diploid_mpet" \
    2> links.log
)
