#!/usr/bin/env bash

set -eu

input_reads="data/20170621_0351_ASW_12_05X_SPRI/merged.fq.gz"
outdir="output/porechop_bbduk"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# bbduk contaminants
 fref="bin/bbmap/resources/phix174_ill.ref.fa.gz,"
fref+="bin/bbmap/resources/sequencing_artifacts.fa.gz,"
fref+="bin/bbmap/resources/adapters_no_transposase.fa.gz"

# log files
porechop_log="${outdir}/porechop.log"
bbduk_log="${outdir}/bbduk.log"

printf "[ %s: Trimming and filtering ]\n" "$(date)"
porechop -i "${input_reads}" --threads 20 \
    2> "${porechop_log}" \
    | bin/bbmap/bbduk.sh threads=20 -Xmx100G \
    in=stdin.fastq \
    "out=${outdir}/trimmed.fastq.gz" \
    minavgquality=6 \
    ziplevel=9 \
    "ref=${fref}" \
    k=23 hdist=2 mink=10 hdist2=1 \
    "stats=${outdir}/stats.txt" \
    "bhist=${outdir}/bhist.txt" \
    "qhist=${outdir}/qhist.txt" \
    "qchist=${outdir}/qchist.txt" \
    "aqhist=${outdir}/aqhist.txt" \
    "bqhist=${outdir}/bqhist.txt" \
    "lhist=${outdir}/lhist.txt" \
    "gchist=${outdir}/gchist.txt" \
    2> "${bbduk_log}"
